<?php
    namespace Config;
/**
 * Generated by framework installer - Thu, 22 Oct 2020 14:38:22 +0200
*/
    class Config
    {
        public const BASEDNAME	= '/webproject';
        public const PUTORPATCH	= 'PATCH';
        public const SESSIONNAME	= 'PSIwebproject';
        public const DBTYPE	= 'mysql';
        public const DBHOST	= 'localhost';
        public const DB	= 'webproject';
        public const DBUSER	= 'webproject';
        public const DBPW	= 'FUK(f/K]}p+H(7BW';
        public const SITENAME	= 'webproject';
        public const SITENOREPLY	= 'noreply@localhost.org';
        public const SYSADMIN	= 'mcnika1234@gmail.com';
        public const DBRX	= FALSE;
        public const REGISTER	= FALSE;
        public const CONFEMAIL	= FALSE;
        public const UPUBLIC	= FALSE;
        public const UPRIVATE	= FALSE;
        public const RECAPTCHA	= 0;
        public const RECAPTCHAKEY	= 'webproject';
        public const RECAPTCHASECRET	= 'webproject';
        public const USEPHPM	= FALSE;
        public const SMTPHOST	= '';
        public const SMTPPORT	= '';
        public const PROTOCOL	= '';
        public const SMTPUSER	= '';
        public const SMTPPW	= '';

        public static function setup()
        {
            \Framework\Web\Web::getinstance()->addheader([
            'Date'                   => gmstrftime('%b %d %Y %H:%M:%S', time()),
            'Window-Target'          => '_top',      // deframes things
            'X-Frame-Options'	     => 'DENY',      // deframes things: SAMEORIGIN would allow this site to use frames
            'Content-Language'	     => 'en',
            'Vary'                   => 'Accept-Encoding',
            'X-Content-Type-Options' => 'nosniff',
            'X-XSS-Protection'       => '1; mode=block',
            ]);
        }


        public static $defaultCSP = [
                'connect-src' => ["'self'"],
                'default-src' => ["'self'"],
                'font-src' => ["'self'", "data:", "*.fontawesome.com"],
                'img-src' => ["'self'", "data:"],
                'script-src' => ["'self'", "stackpath.bootstrapcdn.com", "cdnjs.cloudflare.com", "code.jquery.com", "*.fontawesome.com"],
                'style-src' => ["'self'", "*.fontawesome.com", "stackpath.bootstrapcdn.com"],
        ];
    }

?>